# Generated by Django 2.2.16 on 2022-03-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titles',
            old_name='categorie',
            new_name='category',
        ),
    ]
